# File for Pull Request on main branch
name: CI

# When a PR is opened to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  build:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Node versions
        node-version: [14.x, 16.x]

    # Pipeline Steps
    steps:
      #1 - Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      #2 - Make sure we have all branches
      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin main

      #3 - Run initial node setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      #4 - Clean up folders and run a new install
      - name: Install Dependencies
        run: |
          rm -rf node_modules && rm -rf dist && rm -rf docs && rm -rf coverage
          npm ci

      #5 - Run Linting
      - name: Run Lint
        run: ./.github/scripts/run-linting.sh False

      #6 - Run Tests
      - name: Run Tests
        run: ./.github/scripts/run-testing.sh False
